### ISSUE TITLE
Change text color displayed in RStudio console

### ISSUE THREAD

**Issue by GitHunter0** [daroczig/logger#107]
Hi folks, awesome package. 

Is there a way to change the text color displayed in the RStudio console?

For example, I would like it to use the same color as `print()` and `rlang::inform()`.

Thank you

**Comment by daroczig** [comment]
That would need a custom layout function, and although passing a color palette should be fairly easy, I'm still opposed a bit to provide a helper for that, as I'm pretty sure others might want to use the same colors, but different structure etc so trying to keep it general enough to take arguments would get too complex, if not impossible.

So I'd suggest creating your own coloring function like [`colorize_by_log_level`](https://github.com/daroczig/logger/blob/e32849375f101705a95c74e8edbb3a849a605a9b/R/color.R#L1-L35), then use it via `layout_glue_generator` like in the [`layout_glue_colors`](https://github.com/daroczig/logger/blob/e32849375f101705a95c74e8edbb3a849a605a9b/R/layouts.R#L70-L107) example.

Sorry for not being more supportive, but I hope this helps.
