### ISSUE TITLE
Q: How to set log_threshold by string?

### ISSUE THREAD

**Issue by tentacles-from-outer-space** [daroczig/logger#108]
How to set `logger::log_threshold` when level is provided as string or something else (int?)?

Real life case: I want to set threshold level in parameterized Rmarkdowns (as one of parameters). So I was thinking about something like `rmarkdown::render("x.Rmd", params = list(my_level="TRACE"))` but I don't know what to do with this string. There is no `as.loglevel` function.

**Comment by daroczig** [comment]
Hm, I think a `getFromNamespace` might be enough for the above, but I like the idea of `as.loglevel` so adding that in a bit.
