### ISSUE TITLE
.topenv cannot be supplied to log_info()

### ISSUE THREAD

**Issue by MichaelChirico** [daroczig/logger#140]
```r
log_info("...", .topenv = .GlobalEnv)
# Error in log_level(INFO, ..., .logcall = sys.call(), .topcall = sys.call(-1),  : 
#   formal argument ".topenv" matched by multiple actual arguments
```

This looks to be WAI based on the documentation of `...`, but still threw me off. Maybe a friendlier error here? Perhaps if there are any named arguments to `...`?

**Comment by daroczig** [comment]
added friendly error msg at #141, pls review

**Comment by daroczig** [comment]
the proper solution might be introducing `.topenv` and the other similar args for the `log_info` etc helpers, continuing passing the higher-level `frame` down. I'd highly appreciate a PR, otherwise I'll try to get this in a couple of weeks
