### ISSUE TITLE
CRAN release Q1 2024

### ISSUE THREAD

**Issue by daroczig** [daroczig/logger#144]
Tickets to be resolved before release:

- #26
- #61
- #66
- #73
- #78
- #83
- #84
- #89
- #109
- #114
- #115
- #130 
- #131
- #132
- #136 

PRs to be investigated (hopefully merged) before release:

- #106
- #133 
- #134
- #135
- #142
- #143 :heavy_check_mark: 
- #145 :heavy_check_mark: 
- #146 :heavy_check_mark: 
- #147 :heavy_check_mark: 

Other tasks:

- [x] Update NEWS
- [x] R CMD check passes on R devel
- [x] winbuilder
- [ ] revdepchecks

**Comment by daroczig** [comment]
```
The following package was uploaded to CRAN:
===========================================

Package Information:
Package: logger
Version: 0.3.0
Title: A Lightweight, Modern and Flexible Logging Utility
Author(s): Gergely Daróczi [aut, cre]
  (<https://orcid.org/0000-0003-3149-8537>), System1 [fnd]
Maintainer: Gergely Daróczi <[daroczig@rapporter.net](mailto:daroczig@rapporter.net)>
Suggests: glue, pander, jsonlite, crayon, slackr (>= 1.4.1),
  RPushbullet, telegram, testthat, covr, knitr, rmarkdown,
  devtools, roxygen2, parallel, rsyslog, shiny, callr, txtq,
  botor, R.utils, syslognet
Description: Inspired by the the 'futile.logger' R package and 'logging'
  Python module, this utility provides a flexible and
  extensible way of formatting and delivering log messages with
  low overhead.
License: AGPL-3
Imports: utils
```

:crossed_fingers:

**Comment by daroczig** [comment]
Hit some errors while running the reverse dependency checks :sweat: 
I'm going through the errors and will resubmit.

**Comment by daroczig** [comment]
Opened 2 tickets in downstream packages: 1 bug report in `mtdesign` and checking on a test case in `azlogr`. Reverted/updated the related PRs in `logger` to make all reverse dependency checks pass, and will resubmit soon after all checks were confirmed.

**Comment by daroczig** [comment]
Submitted to CRAN.

**Comment by daroczig** [comment]
Dear maintainer,

thanks, package logger_0.3.0.tar.gz is on its way to CRAN.

Best regards,
CRAN teams' auto-check service
Package check result: OK

No changes to worse in reverse depends.

:tada:

**Comment by m7pr** [comment]
Thanks @daroczig . You are a legend!
