### ISSUE TITLE
Weird error when message is json

### ISSUE THREAD

**Issue by dselivanov** [daroczig/logger#15]
Latest version from master branch:

```r
library(logger)
log_threshold(DEBUG)
log_info(jsonlite::toJSON(list("key" = "value")))
```

>Error in parse(text = text, keep.source = FALSE) : 
  <text>:1:7: unexpected '['
1: "key":[
          ^

**Comment by daroczig** [comment]
Hm, that's coming from the default formatter, `glue`:

```r
          ^
> glue::glue(jsonlite::toJSON(list("key" = "value")))
Error in parse(text = text, keep.source = FALSE) : 
  <text>:1:7: unexpected '['
1: "key":[
          ^
```

I think in this case using another formatter fn or skipping that altogether might make sense, eg

```r
> log_info(skip_formatter(as.character(jsonlite::toJSON(list("key" = "value")))))
INFO [2019-01-17 13:30:31] {"key":["value"]}
```

Thoughts?

**Comment by daroczig** [comment]
Also, can you please elaborate on what kind of log structure do you try to achieve with this?

**Comment by dselivanov** [comment]
>  think in this case using another formatter fn or skipping that altogether might make sense, eg
I think i should work out of the box... if the issue is with glue, we may need to report.

> can you please elaborate on what kind of log structure do you try to achieve with this

Structured logging - make it easy to parse logs - if the message is not just a string, but have some structure.

**Comment by daroczig** [comment]
> I think i should work out of the box... if the issue is with glue, we may need to report.

Well, the JSON has curly braces and `glue` tries to interpret the stuff in between those as R, so that failure is kind of normal. We might have a workaround like skipping the formatter fn if failing, but not sure.

> Structured logging - make it easy to parse logs - if the message is not just a string, but have some structure.

I think that will require a new structure .. .as currently whatever you pass to the logger, that will be passed further as `msg`, see eg:

```r
> log_layout(layout_json())
> log_info('foobar')
{"time":"2019-01-17 14:08:37","level":"INFO","ns":"global","ans":"global","topenv":"R_GlobalEnv","fn":"NA","node":"nevermind","arch":"x86_64","os_name":"Linux","os_release":"4.15.0-20-generic","os_version":"#21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018","pid":16621,"user":"daroczig","msg":"foobar"}

> x <- 42
> log_eval(x, INFO)
{"time":"2019-01-17 14:09:02","level":"INFO","ns":"logger","ans":"global","topenv":"logger","fn":"log_eval","node":"nevermind","arch":"x86_64","os_name":"Linux","os_release":"4.15.0-20-generic","os_version":"#21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018","pid":16621,"user":"daroczig","msg":"'x' => '42'"}
```

**Comment by vpanfilov** [comment]
@daroczig  `glue()` by default treats curly braces as delimeters for string interpolation. So it tries to parse the contents of `{"key":["value"]}` as R code and execute it.

So **logger** should provide an option to override expected delimeters for `glue()`. For example:

``` r
glue::glue('{"key":["value"]}')
#> Error in parse(text = text, keep.source = FALSE): <text>:1:7: íåîæèäàííûé '['
#> 1: "key":[
#>           ^

msg <- "It works!"
glue::glue('{"key":["value"]} - ${msg}$', .open = "${", .close = "}$")
#> {"key":["value"]} - It works!
```

<sup>Created on 2019-03-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by daroczig** [comment]
> @daroczig glue() by default treats curly braces as delimeters for string interpolation. So it tries to parse the contents of {"key":["value"]} as R code and execute it.

Yeah, we have the same understanding. But as per above, I think for JSON logging, you do not really want to use `glue` as the formatter, but instead using JSON for the layout. Anyway, if someone really needs this, a custom formatter (eg what you have shared above) totally works :+1: 

Sorry for no real updates on this ticket so far ... but I don't see a universal solution. Probably better error handling / error message in such case might work? Not sure if a logging fn should fail ... but silent failures are also not cool.

**Comment by daroczig** [comment]
Improved error message might help with this? 

```r
> log_info(jsonlite::toJSON(list("key" = "value")))
Error in value[[3L]](cond) : `glue` failed in `formatter_glue` on:

  'json' chr "{\"key\":[\"value\"]}" 

 with error message:

 <text>:1:7: unexpected '['
1: "key":[
          ^ 

Please consider using another `log_formatter` or `skip_formatter` on strings with curly braces
```

**Comment by daroczig** [comment]
The above suggestion with improved error msg has been merged -- sorry, really no better idea here than using another (eg not `glue`)  formatter when writing JSON messages (before passing to the layout fn).
