### ISSUE TITLE
README: `version-ago` badge display broken

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [daroczig/logger#166]
https://github.com/daroczig/logger/blob/088b6796b333432b7e8b751c0e1cb9cc131aa791/README.md?plain=1#L11

The HTTPS version `https://www.r-pkg.org/badges/version-ago/logger` should work better.

**Comment by daroczig** [comment]
thanks for the report, there's a fix pending review at #162 -- planning to merge today
