### ISSUE TITLE
Restyle logger?

### ISSUE THREAD

**Issue by hadley** [daroczig/logger#174]
Would you be open to a PR that applied `styler::style_dir(".")` to logger? Currently the number of spaces used for indenting seems to vary between 2 and 4 in different parts of the code base.

It would also be nice to wrap the roxygen comments to ~80 characters too.

**Comment by daroczig** [comment]
Yes, please. I've started with four spaces and simple quotes, but it got indeed mixed up via contributions over the years. I'm not even sure why I didn't set up a linter for this repo :scream:

**Comment by daroczig** [comment]
@hadley could you please a look at the above? I don't want to merge this before your approval as you have quote a few pending PRs.
