### ISSUE TITLE
Getting number of active indices

### ISSUE THREAD

**Issue by WurmPeter** [daroczig/logger#180]
Hello Gergely,

Recently I had the need to be able to remove logging to file (index 2) IF EXISTS. ```logger::delete_logger_index``` needs an index, so I had to use a internal function to be able to get the number of active indices first:
```r
loggers <- get(logger:::fallback_namespace("global"), envir = logger:::namespaces)
logger_indices <- length(loggers)
```
 
 Are you open for a PR to include a little public function that just returns the number of current indices (logger_indices)? Or is it just better to change ```fallback_namespace``` so it's a public available function?

**Comment by daroczig** [comment]
That's a good point, thanks for raising this.

I'd not expose `fallback_namespace`, so I'd prefer a new fn, similar to `log_namespaces`, and maybe call it `log_indices` to be consistent with that naming?

I'd appreciate if you can create a PR for that fn taking a single argument for the `namespace`, which is then internally passed to `fallback_namespace`.
