### ISSUE TITLE
master -> main

### ISSUE THREAD

**Issue by daroczig** [daroczig/logger#183]
This repo was created quite some time ago ... but it is better to rename the `main` branch late than never. Let's do this once most PRs have been merged.

**Comment by hadley** [comment]
I can almost guarantee I won't be making any PRs next week since I will be at posit::conf 😄

**Comment by daroczig** [comment]
Next week it is then :sweat_smile:
Have a great time at the posit::conf! And thanks for all the awesome recent work on `logger`.

**Comment by daroczig** [comment]
This is now done. Note that if you have a pending PR, you might need to update to `main` via

```
git branch -m master <BRANCH>
git fetch origin
git branch -u origin/<BRANCH> <BRANCH>
git remote set-head origin -a
```
