### ISSUE TITLE
log logger names

### ISSUE THREAD

**Issue by dselivanov** [daroczig/logger#2]
what about logger names? for example python logging module provides  this functionality. It will be useful to understand from which logger message comes.

Also FYI - my attempt to create simple logging class in RestRserve - https://github.com/dselivanov/RestRserve/blob/master/R/logging.R

**Comment by daroczig** [comment]
I think the `namespace` in the `logger` R package is analogous to the `name` in Python's `logging` module -- except for it doesn't support dot-separated hierarchy. But something like that can be achieved by `namespace` + `index` I think.

**Comment by daroczig** [comment]
Closing this for now, but pls reopen if I misunderstood and/or it seems that the current `namespace` approach doesn't really do this

**Comment by dselivanov** [comment]
Don't you think it makes sense to print logger name in default layouts?
