### ISSUE TITLE
Add size quota or log rotation to appender_file

### ISSUE THREAD

**Issue by bkt0031** [daroczig/logger#31]
Many enterprise companies require some kind of log file size management to assure that the disk won't get filled with logs causing server instability. Log4j has this capability with the RollingFileAppender class where you specify the log size threshold to roll on, and the number of rolling logs to keep. Looking at all of the R logging packages I can find no such feature. It would be nice if logger supported this capability so that I can use it on some of the autonomous R scripts I have running on servers.

**Comment by s-sen** [comment]
I am also looking for an option to do rolling logs. Currently one way to do this is to invoke the log_appender with the log file name (which has the date as suffix) on every call for R services in a long running container. Is there any other way to achieve this e.g. using any configuration?

**Comment by daroczig** [comment]
I've been thinking about this for a while and introducing a basic logrotate would not require much work within the package, so planning to do that.

**Comment by daroczig** [comment]
@bkt0031 @s-sen could you please test #42? I think that delivers the functionality you are looking for.
