### ISSUE TITLE
timeline for CRAN release?

### ISSUE THREAD

**Issue by r2evans** [daroczig/logger#40]
I apologize, this is not really a good issue, but ...

Do you have an expectation of CRAN release of your recent code? I can always install from this source, but I have production locations in which I prefer to stick with "production" releases. (I'm particularly looking forward to `log_errors`, et al.)

**Comment by daroczig** [comment]
Have been trying to do that in the past weeks, but got delayed with that, sorry.

Now that `botor` is on CRAN, this could happen at any time -- I just want to add a couple of small features to close some issues and push a new version. Planning to do that no later by the end of the month :crossed_fingers:

**Comment by r2evans** [comment]
Please don't apologize! I'm not asking you to hurry up your altruistic efforts. Thanks for the package!
