### ISSUE TITLE
Shiny logging with plotly creates empty lines on hover

### ISSUE THREAD

**Issue by wfjvdham** [daroczig/logger#41]
When using `log_shiny_input_changes()` in an app displaying a plotly plot, I get a lot of empty logging lines when hovering the graph. Can hovers be filtered out of the logging? Also it would be nice if you can set the log levels. For the rest a very nice feature :)

```{r}
library(shiny)
library(plotly)
library(logger)

shinyApp(
  ui = fluidPage(
    plotlyOutput("plot"),
    selectInput("test", "test", choices = c("a", "b", "c"))
  ),
  server = function(input, output, session) {
    log_shiny_input_changes(input)
    
    output$plot <- renderPlotly({
      plot_ly(mtcars, x = ~mpg, y = ~wt, mode = "markers", type = "scatter")
    })
  }
)
```

**Comment by daroczig** [comment]
Thanks for this report! I've just pushed 2 commits hopefully fixing both your concerns, please test and let me know how it works.
