### ISSUE TITLE
Inconsistent default date formats

### ISSUE THREAD

**Issue by burgikukac** [daroczig/logger#43]
Just a question, 
in the various layouts the default date formats are not consistent:

while layout_simple or logging has "%Y-**%m-%d**" as default, layout_glue has "%Y-**%d-%m**" (a strange format for me)

Does it have an underlying motive or is it just a typo?

**Comment by daroczig** [comment]
Oh, wow -- good catch, thanks.

That's just a typo in the glue layouts :man_facepalming: 

Could you please open a PR to fix this?

**Comment by burgikukac** [comment]
Did it. I hope it went well as this was my very first PR.

**Comment by daroczig** [comment]
Awesome, thanks :+1:
