### ISSUE TITLE
Vary formatter within appender_tee

### ISSUE THREAD

**Issue by TylerGrantSmith** [daroczig/logger#45]
Is there a way to combine, for example, the `layout_glue_colors` formatter for the console half of an `appender_tee` and no formatter for file half of the tee?

**Comment by daroczig** [comment]
If you need separate `formatter` for the console and the file, then you can do that by dropping `appender_tee` and using two appenders, something like:

```r
library(logger)
log_layout(layout_glue_colors, index = 1)
log_layout(layout_blank, index = 2)
log_appender(appender_console, index = 1)
log_appender(appender_file(...), index = 2)
```

I hope that makes sense -- please reopen if not.
