### ISSUE TITLE
Get the Parent's fn name or get name of function in mapping calls.

### ISSUE THREAD

**Issue by KoderKow** [daroczig/logger#48]
This may be similar to issue #20 . I want to output the fn name to the console and/or output file within a purrr map. For a console example:

``` r
`%>%` <- magrittr::`%>%`

## Custom logger output for console
## output: level, time, function name, message
r_log <- logger::layout_glue_generator(
  format = paste(
    '{crayon::bold(colorize_by_log_level(level, levelr))}',
    '[{crayon::italic(format(time, "%Y-%m-%d %H:%M:%S"))}]',
    '{crayon::underline(fn)}{crayon::underline("()")}:',
    '{msg}'
  )
)

## Set custom output for all loggers
logger::log_layout(r_log)

## purrr ----
x <- 1:3 %>% 
  purrr::map(~ {
    logger::log_info("Adding {.x} to 1")
    .x + 1
  })
#> INFO [2020-04-06 13:00:01] .f(): Adding 1 to 1
#> INFO [2020-04-06 13:00:01] .f(): Adding 2 to 1
#> INFO [2020-04-06 13:00:01] .f(): Adding 3 to 1

## Make it a function
add_1 <- function(.x) {
  logger::log_info("Adding {.x} to 1")
  .x + 1
}

x <- 1:3 %>% 
  purrr::map(add_1)
#> INFO [2020-04-06 13:00:01] .f(): Adding 1 to 1
#> INFO [2020-04-06 13:00:01] .f(): Adding 2 to 1
#> INFO [2020-04-06 13:00:02] .f(): Adding 3 to 1

## lapply ----
## Same thing applies to lapply
x <- 1:3 %>% 
  lapply(function(.x) {
    logger::log_info("Adding {.x} to 1")
    .x + 1
  })
#> INFO [2020-04-06 13:00:02] FUN(): Adding 1 to 1
#> INFO [2020-04-06 13:00:02] FUN(): Adding 2 to 1
#> INFO [2020-04-06 13:00:02] FUN(): Adding 3 to 1

x <- 1:3 %>% 
  lapply(add_1)
#> INFO [2020-04-06 13:00:02] FUN(): Adding 1 to 1
#> INFO [2020-04-06 13:00:02] FUN(): Adding 2 to 1
#> INFO [2020-04-06 13:00:02] FUN(): Adding 3 to 1
```

<sup>Created on 2020-04-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Is there a way within `logger::log_info` to get the parent functions name if it is called within another function? I wasn't sure if we could change the  `.logcall`, `.topcall`, or `.topenv` params to get the functions name to print out or if there was another approach to use fn names. Any help in this matter would be greatly appreciated!

Example 2:
``` r 
i_want_this_name <- function(message, .x) {
  print(message)
  x <- 1:.x %>% 
    purrr::map(add_1)
  return(NULL)
}

x <- i_want_this_name(
  message = "Hello! Adding 1 to every integer to every number up to .x!",
  .x = 3
)
#> [1] "Hello! Adding 1 to every integer to every number up to .x!"
#> INFO [2020-04-06 13:06:36] .f(): Adding 1 to 1
#> INFO [2020-04-06 13:06:36] .f(): Adding 2 to 1
#> INFO [2020-04-06 13:06:36] .f(): Adding 3 to 1
```

Thanks!

**Comment by smingerson** [comment]
If your functions with logging are always predictably nested (i.e. only 1 function deep and called within a map), you can fiddle with `sys.call()` . This can get dicey. For example, I was going to put this in a reprex, but that changed the function reported to `tryCatch()`, not `i_want_this_name`.

```
library(logger)
library(magrittr)
r_log <- logger::layout_glue_generator(
  format = paste(
    '{crayon::bold(colorize_by_log_level(level, levelr))}',
    '[{crayon::italic(format(time, "%Y-%m-%d %H:%M:%S"))}]',
    '{crayon::underline(sys.call(1)[[1]])}{crayon::underline("()")}:',
    '{msg}'
  )
)

## Set custom output for all loggers
logger::log_layout(r_log)
add_1 <- function(.x) {
  logger::log_info("Adding {.x} to 1")
  .x + 1
}

i_want_this_name <- function(message, .x) {
  print(message)
  x <- 1:.x %>% 
    purrr::map(add_1)
  return(NULL)
}

x <- i_want_this_name(
  message = "Hello! Adding 1 to every integer to every number up to .x!",
  .x = 3
)
#[1] "Hello! Adding 1 to every integer to every number up to .x!"
#INFO [2020-06-25 13:51:35] i_want_this_name(): Adding 1 to 1
#INFO [2020-06-25 13:51:35] i_want_this_name(): Adding 2 to 1
#INFO [2020-06-25 13:51:35] i_want_this_name(): Adding 3 to 1
```

**Comment by daroczig** [comment]
Thanks a lot for raising this question -- which is an interesting (and not easy) problem.

I think the main issue is that map and its friends related to functional programming usually doesn't preserve the fn name, just the fn body, so eg tracking down `add_1` is kind of impossible in a such setup .. see #20 for more details.

So I'll focus on your second point, and how to use the parent function name for `{fn}`. Unfortunately, `purrr` the `magrittr` also introduces some complexities here when it comes to tracking down the actual parent call.

One could try to resolve that with moving away from auto-guessing in `{fn}` as @smingerson suggested above, or manually keep track of the call stack and do that not at the general log layout level, but inside your function, eg:

```r
add_1 <- function(.x) {
    logger::log_level(INFO, glue::glue("Adding {.x} to 1"), .topcall = sys.call(-10))
    .x + 1
}

i_want_this_name <- function(message, .x) {
    print(message)
    x <- 1:.x %>%
        purrr::map(add_1)
    return(NULL)
}

x <- i_want_this_name(
  message = "Hello! Adding 1 to every integer to every number up to .x!",
  .x = 3
)
#> INFO [2020-06-27 12:22:09] i_want_this_name(): Adding 1 to 1
#> INFO [2020-06-27 12:22:09] i_want_this_name(): Adding 2 to 1
#> INFO [2020-06-27 12:22:09] i_want_this_name(): Adding 3 to 1
```

Honestly, I'm not sure if any automated way of guessing which function name to log here will work nicely for all cases ... I'd rather suggest in such case to log the fn name (reference) manually in the log message, and let `logger` log whatever `{fn}` it can identify if you are a heavy user of `Map` et al.

As there's no clear further steps to work on this, I'm closing, but feel free to reopen if you have any suggestions.
