### ISSUE TITLE
Add a new release in CRAN

### ISSUE THREAD

**Issue by korlaz** [daroczig/logger#49]
Hello,

Would it be possible to do a new release and publish it to CRAN ?

Thanks !

**Comment by aecoleman** [comment]
I would like to chime in to say that I would also appreciate this. It appears that the glue colors layout datestamp issue still exists in the CRAN release, and the CRAN release is missing the (excellent) revolving logs feature.

**Comment by daroczig** [comment]
I've spent a couple of hours on cleaning up the package and planning to submit to CRAN later today :crossed_fingers:

**Comment by daroczig** [comment]
The submission didn't go well 2 weeks ago, so I will try again this weekend.

**Comment by shosaco** [comment]
any updates on this one? I am loving this package and am installing from Github and would prefer to do so from CRAN, anything we can do for the release?

**Comment by daroczig** [comment]
fe977c8e09fc6d088cfb77e4e01dc9e0e853a1cc submitted today :crossed_fingers:

**Comment by shosaco** [comment]
Hi! Still using your Github HEAD in my renv.lock, any news on the CRAN release? :-)

**Comment by daroczig** [comment]
Sorry folks, I tried to submit 2 times (June and November of 2020) with a comment to the CRAN maintainers on a false positive `NOTE` in `R CMD check`, but without success to getting any response ... since then, I think I may have a workaround to suppress that `NOTE` but the workaround is I think uglier than having a false `NOTE` so have been hesitant doing that -- anyway, thanks for following up, I will go ahead with that for now.

**Comment by marekrogala** [comment]
Thanks for pushing with this @daroczig
I would also appreciate a new release on CRAN as I'm using logger in a new package that I also want to send to CRAN.

**Comment by jozefhajnala** [comment]
Hi @daroczig , just another vote for getting a more recent version of logger to CRAN. 
Also, if there is something specific I could help with with regards to the release, I am happy to help.
Thanks!

**Comment by daroczig** [comment]
Giving it a try today :crossed_fingers:

**Comment by daroczig** [comment]
> The package has been uploaded successfully to CRAN

:zipper_mouth_face: :crossed_fingers:

**Comment by daroczig** [comment]
> thanks, package logger_0.2.0.tar.gz is on its way to CRAN
