### ISSUE TITLE
Including a simple text to log without any header

### ISSUE THREAD

**Issue by kbzsl** [daroczig/logger#55]
Is it possible to include a simple text (like an SQL query, ...) without any header (level, timestamp), whilst keeping the set layout for everything else?

For example, my current implementation using multiple `log_info()`
```
log_info("SQL query")
tictoc::tic("SQL query")
log_info(query)
# query …
log_info(capture.output(tictoc::toc()))
```
and the result:
```
INFO [2020-07-22 07:20:16] SQL query
INFO [2020-07-22 07:20:16] SELECT "Content ID", "Content Title"
FROM "Content Table"
INFO [2020-07-22 07:20:41] SQL query: 25.58 sec elapsed
```
but the preferred result would be something like:
```
INFO [2020-07-22 07:20:16] SQL query
SELECT "Content ID", "Content Title"
FROM "Content Table"
INFO [2020-07-22 07:20:41] SQL query: 25.58 sec elapsed
```

**Comment by razz-matazz** [comment]
I created a function that backs up the old layout, overrides it for this log entry and then restores the layout. 

logSQL <- function(msg) {
  logger.layout.console.previous <- logger::log_layout()
  logger.layout.console <- logger::layout_glue_generator(format = paste('{msg}'))
  logger::log_layout(logger.layout.console)
  logger::log_level(logger::INFO, msg)
  logger::log_layout(logger.layout.console.previous)
}

Maybe it's useful for you.

**Comment by daroczig** [comment]
> I created a function that backs up the old layout, overrides it for this log entry and then restores the layout.

If it would be useful in your case, it would be trivial to add a function to the package that does this, similar to `with_log_threshold`. Please feel free to open a related ticket (or even better, a PR).

On the other hand, it might be more elegant to solve the above with the use of namespaces in `logger`. See https://daroczig.github.io/logger/articles/customize_logger.html#log-namespaces-1

Offtopic, but regarding your SQL query helper -- have you seen `dbr`? See eg https://github.com/daroczig/dbr#querying-databases

**Comment by daroczig** [comment]
As per above, namespaces already support this and a helper could be also created -- but not sure if that's still something the OP might need, so closing the ticket. Please reopen if you have any further feedback.
