### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by razz-matazz** [daroczig/logger#56]
Hello,

I am enjoying logger so far. Today I encountered a problem with UTF-8.
I use two appenders - one for console (index 1), one for file output (index 2).

I try to log the phrase "wurde geöffnet" (german for "x has been opened") 

logger::log_trace("x wurde geöffnet"): 
output in file: "wurde geöffnet"
output in console: "wurde geÃ¶ffnet"
 
logger::log_trace(enc2utf8("x wurde ge\u00F6ffnet")):
output in file: "wurde ge?ffnet"
output in console: "wurde geöffnet"

I am on Windows 10, Rstudio 1.3..1056, R 4.0.2. 
Sys.setlocale("LC_TIME", "German")

BTW: Is there a way to do reverse file logging? I'd like to have the newest entries at top in my log files (or is that considered bad logging style?)

**Comment by daroczig** [comment]
Oh, sorry to hear that :( 

I don't have access to a Windows machine, but trying to debug this. Can you please upload the two log files created by the above two examples?

**Comment by daroczig** [comment]
> BTW: Is there a way to do reverse file logging? I'd like to have the newest entries at top in my log files (or is that considered bad logging style?)

I have not heard about that -- the logger is appending to the file, and I think a prepend will need either rewriting everything in the file, or using a very special filesystem or similar, so not a commonly used approach I think. But you could just load the log records from the file in reverse order if that works for you, eg using `tac` on the command line (vs `cat`).

**Comment by razz-matazz** [comment]
> I don't have access to a Windows machine, but trying to debug this. Can you please upload the two log files created by the above two examples?

I just discovered that the file opened in Windows Editor or MS Visual Studio 2017 shows the german umlaut, RStudio or Code Writer do not. 

[p_2020-08-31.log](https://github.com/daroczig/logger/files/5149380/p_2020-08-31.log)

**Comment by daroczig** [comment]
This file seems to have ISO-8859-1 character encoding (probably what you use on your computer, so thus that is being used by default when writing the log file), so you could select that encoding when opening a file in RStudio as per https://support.rstudio.com/hc/en-us/articles/200532197-Character-Encoding

I think that solves your issue, so closing this, but let me know if you run into issues.
