### ISSUE TITLE
log_threshold error when using character input

### ISSUE THREAD

**Issue by stPhena** [daroczig/logger#58]
If `log_threshold()` is called using a character argument, when the package is not attached, it gives the following error:
```
> logger::log_threshold("TRACE")
Error in as.environment("package:logger") : 
  no item called "package:logger" on the search list
```

This would help, for instance, when setting the log threshold using a configuration file (e.g. config.yml).

**Comment by daroczig** [comment]
Can you please test if #59 fixes this?

**Comment by stPhena** [comment]
Works like a charm. Thanks!
