### ISSUE TITLE
auto log errors / warnings / messages like in loggit

### ISSUE THREAD

**Issue by daroczig** [daroczig/logger#6]
https://twitter.com/ryapric/status/1067602852879785984

**Comment by daroczig** [comment]
See eg providing helper fns and suggesting to users to set those as `options('error')` and `options('warning.expression')`

**Comment by daroczig** [comment]
also https://github.com/smbache/loggr

**Comment by daroczig** [comment]
This has been done in 111e905

**Comment by llrs-roche** [comment]
I come here from the [vignette about migration](https://cran.r-project.org/web/packages/logger/vignettes/migration.html) maybe you would like to improve the loggit section. Thanks for the package!
