### ISSUE TITLE
Passwords recorded with log_shiny_input_changes

### ISSUE THREAD

**Issue by pvictor** [daroczig/logger#80]
Hello,

Passwords entered with `passwordInput` are logged with `log_shiny_input_changes`, it can be a little embarrassing.
I don't think there's any way to differentiate `passwordInput` from the other ones server-side.
Maybe add a warning in documentation or the possibility to exclude an input from logging ?

Best,

Victor

**Comment by daroczig** [comment]
Great point -- thanks for reporting this! I've pushed an update at #81 to allow excluding inputs from the auto-logging -- I hope that works, so please test and report back.

**Comment by pvictor** [comment]
Nice, thank you!
Note that if you are using `passwordInput` into shiny modules, you'll have to do something like:

```r
excluded_inputs = c("password", NS("my-module-ID", "password"))
```

Otherwise you'll have to allow regex into `excluded_inputs`, but it should be manageable and resolve the problem already, so thanks!

Victor
