### ISSUE TITLE
Feature request: Log Customization for appender_file and appender_console

### ISSUE THREAD

**Issue by camult** [daroczig/logger#85]
I wonder if it is possible to print different layouts one for the console and another one with more details to a file.

For example:

``` {.r}
logLayoutFile <- "{node} \t {user} \t {pid} \t {time} \t {fn} \t {level} \t {msg}"
logLayoutConsole <- "{fn} {level} {msg}"

logger <- layout_glue_generator(format_console = logLayoutConsole , format_file = logLayoutFile )
log_layout(logger)

```

Thank you.

**Comment by daroczig** [comment]
Sure, I think you are interested in the `index` parameter of the related function for stacking logger configs: https://daroczig.github.io/logger/articles/customize_logger.html#stacking-loggers-1

**Comment by camult** [comment]
Can you provide an example where the log in the console has a different layout from the log saved to a file?
