### ISSUE TITLE
json logging

### ISSUE THREAD

**Issue by dselivanov** [daroczig/logger#9]
I think we can do a little bit better compared to what we [have at the moment](https://github.com/daroczig/logger/blob/8b01a6a401bc2311beb896aa430cbc4b80f7b094/R/layouts.R#L161-L172)

We can serialize arbitrary R object (`msg`) to JSON instead of simple `message = as.character(msg)`. So it can be just:
```r
    toJSON(list(
            level = attr(level, 'level'),
            timestamp = Sys.time(),
            message = msg
        ), auto_unbox = TRUE))
```

**Comment by daroczig** [comment]
Passing `msg` as an object to a layout function is against the design of splitting formatter and layout functions ... so, unfortunately, we won't be able to do that :/ but I've added a bunch of (optional) metadata to the resulting JSON log record, see eg:

```r
> log_layout(layout_json())
> log_info(42)
{"time":"2018-12-18 01:40:27","level":"INFO","ns":"global","ans":"global","topenv":"R_GlobalEnv","fn":"NA","node":"nevermind","arch":"x86_64","os_name":"Linux","os_release":"4.15.0-20-generic","os_version":"#21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018","pid":13622,"user":"daroczig","msg":"42"}
```

I hope you find that useful :)

**Comment by dselivanov** [comment]
What if we will first serialize message to string using `toJSON` instead of `as.character`?

**Comment by daroczig** [comment]
Actually, I think this is what you need: https://github.com/daroczig/logger/compare/c336a377705ed0467b30fbcd4a2a04ac7c871cdf...c3f5641df5efaaddde8618582246b19c9a85f7f2#diff-727a9774377a04a50a6e9204c669e838R120

**Comment by daroczig** [comment]
sorry, fixed the URL, pls check again when you have a chance: https://github.com/daroczig/logger/compare/c336a377705ed0467b30fbcd4a2a04ac7c871cdf...c3f5641df5efaaddde8618582246b19c9a85f7f2
