### ISSUE TITLE
PSA: log_messages() creates a failure in with future plan(cluster)setups

### ISSUE THREAD

**Issue by 1beb** [daroczig/logger#91]
log_messages is used to sink messages into the logger format. However, on a future cluster (`plan(cluster)`) it creates a problem. I believe this is the same type of problem that occurs with `profvis`.

**Comment by daroczig** [comment]
can you please post a minimal reproducible example of the problem?

**Comment by 1beb** [comment]
I think this is outside of scope for `logger`. On a cluster, each machine would have it's own sink. So instead of sinking to a central log location you would have many, on different machines. I don't think this is a tractable problem without some kind of rdbms.

**Comment by 1beb** [comment]
Sorry, I didn't see the notification back in January! Github notifications can be cluttered sometimes!
