### ISSUE TITLE
log_separator is not working properly for other layouts than layout_simple

### ISSUE THREAD

**Issue by Polkas** [daroczig/logger#95]
Example where the static 23 characters for log header will not work correctly. This 23 characters comes from layout_simple which is assumed to be always used now. 

```r
logger <- layout_glue_generator(format = '{node}/{pid}/{namespace}/{fn} {time} {level}: {msg}')
log_layout(logger)
log_separator(ERROR, separator = '!', width = 80)
```

I already working on that and will add solution to my PR.
This is exposed on log_with_separator too.
I will pin this issue to my PR.

BTW If it should not be supported then roxygen2 docs should be straight forward (that width have to be adjusted for custom layouts).

**Comment by daroczig** [comment]
Thanks for the related fix :bow:
